### ISSUE TITLE
Can't follow the CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by XREvo** [sergiodxa/grial#11]
Hi,
I just wanted to warn you that we can't foloow step 4 from the [CONTRIBUTING.md](https://github.com/sergiodxa/grial/blob/master/CONTRIBUTING.md)
There is no 'build' script in package.json.
What is the best way to do it?
Bye

**Comment by sergiodxa** [comment]
Thanks, you're right I removed the build step so it's not possible to do that anymore. I changed the guideline 😉
