### ISSUE TITLE
Cache DB connection

### ISSUE THREAD

**Issue by antoniopresto** [sergiodxa/grial#12]
Thanks for the awesome framework!
Could we save the connection to databases to reuse in other parts of the application?
Something like:

```javascript
const MongoClient = require("mongodb");

const connectionCache = {};

async function mongodb(URL) {
  if (connectionCache[URL]) return connectionCache[URL];

  const connectionPromise = new Promise((resolve, reject) => {
    MongoClient.connect(URL, (error, connection) => {
      if (error) return reject(error);
      resolve(connection);
    });
  });

  connectionCache[URL] = connectionPromise;
  return connectionPromise;
}

exports.mongodb = mongodb;

**Comment by sergiodxa** [comment]
Yes, you can try implementing a custom connector to do that or just don't use connectors at all, instead you can handle your DB connections your self, with a `grial.config.js` you can pass them as context or you can require them directly in your resolvers too.

**Comment by antoniopresto** [comment]
Yes, I did. I was wondering if it would be appropriate to send PR with this (But I did not write that right).

I thought it would be nice if we could provide the server as an argument instead of creating one automatically. What do you think?

Sorry if this is not the channel for these issues.

**Comment by sergiodxa** [comment]
Well right now you can create your own HTTP server and use @grial/server only to read your connections, models, schema and resolvers and get a request handler for `/graphql` and `/ide`.

https://github.com/sergiodxa/grial/tree/master/server#custom-usage

But if you have and idea about the cache PR are welcomed!

**Comment by antoniopresto** [comment]
I'll send the PR. Thanks
