### ISSUE TITLE
remove file extension from required files

### ISSUE THREAD

**Issue by joernroeder** [sergiodxa/grial#15]
By removing the file extension from the import of [e.g.`resolvers.js`](https://github.com/sergiodxa/grial/blob/db3650b75129844548ef4bfa5bfa9bd2398ed1d7/server/api/resolvers.js#L5) we'd be able to import `resolvers.js` or `resolvers/index.js` which acts as an entry point and reexports all resolvers.
I've seen that you have basically implemented the same concept for `schema.ggl|grapgl` and files within the `schemas/*.ggl|graphql` folder and it's a common concept to structure your application.

I'll help with a implementation in the future, just let me know what do you think…

**Comment by sergiodxa** [comment]
Hi, if you want to send a PR that would be great!

**Comment by antoniopresto** [comment]
I think it's possible to use  [node-glob](https://github.com/isaacs/node-glob) to implement something like this as well

**Comment by joernroeder** [comment]
@sergiodxa hi, i'm pretty busy right now with other projects but i'm trying to come up with something on the weekend.
